---

# Build and test the code, with an optional deploy
name: Build
on: [push, pull_request]
permissions: read-all

jobs:
    pre-commit:
        name: Pre-commit (linting)
        runs-on: ubuntu-latest
        timeout-minutes: 5

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Run pre-commit
              uses: pre-commit/action@v3.0.1

    docker-build:
      name: Docker build
      runs-on: ubuntu-latest
      # Enable Buildkit and let compose use it to speed up image building
      env:
        DOCKER_BUILDKIT: 1
        COMPOSE_DOCKER_CLI_BUILD: 1
      timeout-minutes: 5

      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Build the Docker image
          run: docker build .

    pytest-in-venv:
        name: Python tests
        runs-on: ubuntu-latest
        env:
            APP_ENVIRONMENT: test

        timeout-minutes: 5

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"
                  cache: pip

            - name: Install dependencies
              run: pip install -r requirements/requirements-test.txt

            - name: Run the tests with coverage
              run: pytest --cov=./ --cov-report=xml